export const PRODUCTS_ACTION = {
  FETCH: "PRODUCTS_FETCH",
  UPDATE: "PRODUCTS_UPDATE",
  ERROR: "PRODUCTS_ERROR",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
