name:Node continous Integration
 on:
   pull_request:
    branches: [main]
 jobs:
   test_pull_request:
     runs_on: ubuntu-latest
     steps:
       -uses: actions/checkout@v2
       -uses: actions/setup-node@v1
        with:
           node-version: 16
       -run: npm ci
       -run: npm test
       -run: npm run build
