name: Node CI

on:
  push:
    branches:
    - master
    - release/*
jobs:
  test_pull_request:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
       node-version: '16.x'
    - run: npm install
    - run: npm run build
